### PR TITLE
SRP6 for user auth

### PR DESCRIPTION
**Pull request by Treeston**
_(See also: TrinityCore/TrinityCore#25157.)_

Depends on TrinityCore/TrinityCore#25135 to work.
Will be needed after TrinityCore/TrinityCore#25156.

### CODE REVIEW

**Comment by jackpoz** [comment]
@Sarjuuk do you have time to test this ?

**Comment by Sarjuuk** [comment]
On second thought. 
Should this be a separate branch while it is being deprecated? (timeline mentioned in https://github.com/TrinityCore/TrinityCore/issues/25157)

**Comment by Treeston** [comment]
Up to you, it will be usable with mainline 3.3.5 starting with TrinityCore/TrinityCore#25135's merge.
That PR just began review, so I'd expect it to be merged sometime in the next 2-3 days.

After that, I would expect TrinityCore/TrinityCore#25138 within another few days, at which point config switches would be necessary to keep the current aowow auth functional.

**Comment by Sarjuuk** [comment]
thank you very much for your work and notice.

**Comment by jackpoz** [comment]
just as additional info, gmp php extension is required to use gmp functions (in case the readme has to be updated)

**Comment by Sarjuuk** [comment]
aw shucks..

thanks for reminding me.

**Pull request merged**
